### ISSUE TITLE
Unable to Load Plugin

### ISSUE THREAD

**Issue by niwiniwi** [dmalec/OctoPrint-OctoGlow#4]
Hi, i installed your plugin with the requirements. But when i start OctoPrint i see the following in the logs:

```
2018-03-27 16:35:59,456 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-03-27 16:36:02,050 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugin/core.py:1538: UserWarning: No PKG-INFO found for package: octoprint_octoglow
  warnings.warn('No PKG-INFO found for package: %s' % self.package_name)

2018-03-27 16:36:02,057 - octoprint.plugin.core - ERROR - Error loading plugin octoglow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugin/core.py", line 732, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octoglow/__init__.py", line 8, in <module>
    from piglow import PiGlow
ImportError: cannot import name PiGlow
2018-03-27 16:36:02,179 - octoprint.plugin.core - INFO - Found 28 plugin(s) providing 28 mixin implementations, 28 hook handlers
2018-03-27 16:36:02,307 - octoprint.server - INFO - Intermediary server started
2018-03-27 16:36:02,308 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-03-27 16:36:02,605 - octoprint.plugin.core - ERROR - Error loading plugin octoglow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugin/core.py", line 732, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octoglow/__init__.py", line 8, in <module>
    from piglow import PiGlow
ImportError: cannot import name PiGlow
```

Can you help me please?

**Comment by WLCD** [comment]
Check this post : https://github.com/dmalec/OctoPrint-OctoGlow/issues/5#issuecomment-478898334
